-   id: enforce-primary-secondary
    description: ensure there is a primary and secondary 
    name: enforce primary / secondary  
    entry: enforce-primary-secondary 
    language: ruby
    types: [text]
    stages: [commit, push, manual]
